{"uuid":"924c8d33-3a8b-4763-b94c-aa482e3c41eb","historyId":"ec079bc2f0d0776d10775f9c4cbee14","fullName":"io.cucumber.testng.AbstractTestNGCucumberTests.runScenario","labels":[{"name":"package","value":"ds.algo.testrunner.DSAlgoTestRunner"},{"name":"testClass","value":"ds.algo.testrunner.DSAlgoTestRunner"},{"name":"testMethod","value":"runScenario"},{"name":"parentSuite","value":"Default suite"},{"name":"suite","value":"Default test"},{"name":"subSuite","value":"ds.algo.testrunner.DSAlgoTestRunner"},{"name":"host","value":"DESKTOP-D3D23G2"},{"name":"thread","value":"32940@DESKTOP-D3D23G2.main(1)"},{"name":"framework","value":"testng"},{"name":"language","value":"java"}],"links":[],"name":"Runs Cucumber Scenarios","status":"passed","statusDetails":{"known":false,"muted":false,"flaky":false},"stage":"finished","steps":[],"attachments":[],"parameters":[{"name":"arg1","value":"\"Test Tree Page features\""},{"name":"arg0","value":"\"User is able to run invalid code in tryEditor with error message\""}],"start":1681271967928,"stop":1681271970783}